
project:
  type: website
  output-dir: output

website:
  title: "Leslie Hodges Gallagher CV"
  navbar:
    left:
      - href: HodgesGallagher_CV_20250713.qmd
        text: Home

format:
  html:
    theme: none
    css: styles.css
    toc: true
  pdf:
    author: "Leslie Hodges Gallagher, Ph.D."
    pdf-engine: weasyprint
    css: styles.css

format-links: [pdf]
